# Generated by Django 2.1.2 on 2018-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timetables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('teacher', models.CharField(default='', max_length=256)),
                ('level', models.IntegerField()),
                ('week', models.IntegerField()),
                ('time', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('room', models.CharField(default='', max_length=256)),
                ('target_id', models.CharField(default='', max_length=256)),
                ('quater', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
