# Generated by Django 2.1.2 on 2019-01-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='title',
        ),
    ]
