# Generated by Django 2.1.4 on 2019-01-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_devices_notifications_teachers_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(default='', max_length=256)),
                ('token', models.CharField(default='', max_length=256)),
                ('expire', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='timetables',
            name='isNotification',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='IsContact',
            field=models.BooleanField(default=False),
        ),
    ]
