# Generated by Django 2.1.4 on 2019-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20190103_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admission_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='permission_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
