# Generated by Django 2.1.2 on 2018-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_devices_notifications_teachers_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(default='', max_length=256)),
                ('token', models.CharField(default='', max_length=256)),
                ('expire', models.IntegerField()),
            ],
        ),
    ]
