# Generated by Django 2.1.2 on 2019-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_remove_notifications_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
