# Generated by Django 2.1.2 on 2019-01-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_notifications_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device',
            field=models.CharField(default='', max_length=100),
        ),
    ]
