# Generated by Django 2.1.4 on 2019-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20190103_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetables',
            name='isNotification',
            field=models.BooleanField(default=False),
        ),
    ]
