# Generated by Django 2.1.2 on 2018-12-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='University',
            field=models.CharField(default='', max_length=100),
        ),
    ]
