# Generated by Django 2.1.2 on 2019-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20190120_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='token',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devices',
            name='target_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
