# Generated by Django 2.1.2 on 2019-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_notifications_targetteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isProcessOnRails',
            field=models.BooleanField(default=False),
        ),
    ]
