# Generated by Django 2.1.2 on 2019-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_notifications_isprocessonrails'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='offset_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
